### ISSUE TITLE
Move to JuliaLinearAlgebra?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLinearAlgebra/RandomizedLinAlg.jl#11]
Thoughts on moving the package to JuliaLinearAlgebra?

**Comment by haampie** [comment]
Hey @ViralBShah, that sounds good to me. I wasn't a big fan of these methods, so if they could be transferred to a new home that would be better.

**Comment by ViralBShah** [comment]
Thanks. I was just poking around to see what exists, and figured having it in the org might help bring others together who may be interested. Added a Project.toml and some clean up just to make it easy to try out.
